### ISSUE TITLE
Multiple CKEditor5

### ISSUE THREAD

**Issue by wings77** [ckeditor/ckeditor5-core#188] opened 2019-07-12 19:53 UTC
If I have multiple ckeditor, how do I identify them?

`editor.setData( 'text1 );`
`editor.setData( 'text2' );`

**Comment by Mgsy** [comment] 2019-07-15 07:23
Hi, please don't open multiple tickets for one problem. Closing as duplicate of https://github.com/ckeditor/ckeditor5/issues/1883.

**Closed by Mgsy** 2019-07-15 07:23 UTC
