### ISSUE TITLE
Model#bind: instead of listening to model:change, use setters to manipulate bound models

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-core#101] opened 2015-12-02 11:36 UTC
A followup of #93.

**Comment by Reinmar** [comment] 2015-12-04 09:07
Reasoning: https://github.com/ckeditor/ckeditor5-core/pull/94#commitcomment-14682505

**Comment by Reinmar** [comment] 2015-12-04 09:13
> Yes. I also realised that rather than using events, we should implement it the opposite way (for A.bind( 'x' ).to( B )): x attribute setter in B should make changes to A.x rather than A listen to the changes in B and react when B.x has changed. But it was too late when I noticed it.

I'm not sure about this. The communication IMO should be event-based. I know that it's all happening within the `Model` class, but these will be different instances.

What you may not know is that the attribute setters in fire two events – `model#change` and `model#change:attrname`. So just use the second one instead of the first one.

**Comment by oleq** [comment] 2015-12-04 09:40
> What you may not know is that the attribute setters in fire two events – model#change and model#change:attrname. So just use the second one instead of the first one.

I know about this. I went for `model#change` to reduce the number of listeners being attached. On the other hand, you got to attach far more `model#change:attrname` listeners, but they're called not so quite often as `model#change`.

**Comment by Reinmar** [comment] 2015-12-04 09:42
Yeah – memory vs performance fight as usual :).

**Comment by oleq** [comment] 2015-12-04 09:43
Determining which approach proves more beneficial in a long run seems to be very interesting, doesn't it?

**Comment by Reinmar** [comment] 2015-12-04 09:59
The perfect solution will be to add as few listeners as possible, so if two models are bound to some source model, only one listener is added to `source#change:foo`. But listening to `source#change` could never outperform listening to specific changes, because you need to know what has changed.

**And here I understood how wrong I am...** because in `source#change` we know precisely what has changed thanks to the first arg passed to the listener.

So if we're able to code it in a way that there's just a single listener no matter how many models you'll bind to `source`, we could have best of two worlds, because usually all bindings to the source model, combined, will be interested in most of `source`'s changes. Hence, listening on the whole `source#change` makes a lot of sense here. How does it work right now? Are we able to achieve this?

PS. There's one more thing which worries me – cancelling those `change` and `change:attrname` events. I've never liked the fact that there are two of them fired because you cannot know if canceling some event will really have some effect as you don't know if the listener is attached to the general or specific event. At the end you need to listen to both... On the other hand, that's a kind of event which you should rather not cancel, because the fact already happened. So I guess it's OK.

**Comment by oleq** [comment] 2015-12-04 10:24
Let me know if I got your idea right. So when
```
A1.bind( 'x' ).to( B );
A2.bind( 'x' ).to( B );
```
you'd see a single `B#change` listener associated with B, that updates `A1.x` and `A2.x`?

----

Because at the moment, in such case  there are 2 `B#change` listeners attached, associated with `A1` and `A2` rather than with `B`. And it's not to bad because both `A1` and `A2` call `listenTo( B, 'change', ... )`, 

https://github.com/ckeditor/ckeditor5-core/blob/8f43f8a9081cd4276eebb85fbd9c4451230597ac/src/model.js#L491-L493

which does nothing more than `B.on( 'change', ... )`, 

https://github.com/ckeditor/ckeditor5-core/blob/8f43f8a9081cd4276eebb85fbd9c4451230597ac/src/emittermixin.js#L152

which, in turn, puts the `A1.x = B.x` and `A2.x = B.x` callbacks in the poll

https://github.com/ckeditor/ckeditor5-core/blob/8f43f8a9081cd4276eebb85fbd9c4451230597ac/src/emittermixin.js#L42-L48.

So when `B#change` is fired, the program checks twice whether it's really `B#change:x` and those 2 callbacks are executed and do their job.

---

In your implementation you'd check only once whether it's really `B#change:x` and then execute `A1.x = B.x` and `A2.x = B.x` callbacks, stored in some other place. So it's the only advantage that I see here.

**Comment by Reinmar** [comment] 2015-12-04 10:56
It's really hard to tell now. We would need to have some perf tests, which it'll be better to implement once we have more code using this API, because we'll know we're testing the right thing.

If I were to implement it for the first time I would opt for using as little `change` listeners as possible to avoid the overhead caused by executing many listeners, handling super long lists of them in the event emitter, etc. Also, the `bind()` method could become faster as it would only store the information it needs, without calling `on()` which e.g. needs to sort priorities. But this is of course theory.

On the other hand it makes sense to use `listenTo()` because then you can quickly unbind a model from all other models.

**Comment by Reinmar** [comment] 2016-03-10 10:37
Moved to https://github.com/ckeditor/ckeditor5-utils/issues/4

**Closed by Reinmar** 2016-03-10 10:37 UTC
Labels: module:core, status:discussion, type:enhancement, ★★
